### ISSUE TITLE
Some troubles with the plugin

### ISSUE THREAD

**Issue by chichille** [ThibaudArros/toctoc#1]
First of all thank you for your plugin

First: I do not see in the documentation that it is necessary to add a div with ID 'toctoc' otherwise it does not work.
div id="toctoc" before to call $.toctoc();

Second: if the content of 'hx' is surrounded by a link, when you click on the table of contents entry, you open the targeted page and do not scroll down to the link. I suggest when you collect the content of the link, to retrieve it by 'text' and not by 'html'.
Line 34: let content = $(this).text(); vs let content = $(this).html();

If that can help you ...
Rgds

**Comment by Athios-dev** [comment]
Hi @chichille !

Thanks for your feedback, I really appreciate.

1. I actually forgot to specify the declaration of TOC container in the documentation, this is up to date.
2. Indeed, I had not considered the case of titles not containing only text. The jQuery function used is now .text().

Thanks again 👌

Thibaud d'Arros
